// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: auditlogs.sql

package db

import (
	"context"
)

const createLogs = `-- name: CreateLogs :one
INSERT INTO audit_logs (
  account_id,
  action,
  action_type,
  action_description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, account_id, action, action_type, action_description, performed_by, affected_record, timestamp
`

type CreateLogsParams struct {
	AccountID         int64  `json:"account_id"`
	Action            string `json:"action"`
	ActionType        string `json:"action_type"`
	ActionDescription string `json:"action_description"`
}

func (q *Queries) CreateLogs(ctx context.Context, arg CreateLogsParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createLogs,
		arg.AccountID,
		arg.Action,
		arg.ActionType,
		arg.ActionDescription,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Action,
		&i.ActionType,
		&i.ActionDescription,
		&i.PerformedBy,
		&i.AffectedRecord,
		&i.Timestamp,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT id, account_id, action, action_type, action_description, performed_by, affected_record, timestamp FROM audit_logs ORDER BY account_id LIMIT $1 OFFSET $2
`

type ListLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Action,
			&i.ActionType,
			&i.ActionDescription,
			&i.PerformedBy,
			&i.AffectedRecord,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
