// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type AuditLog struct {
	ID        int64          `json:"id"`
	AccountID int64          `json:"account_id"`
	Action    sql.NullString `json:"action"`
	Timestamp sql.NullTime   `json:"timestamp"`
}

type Deposit struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type PortfolioBalance struct {
	ID          int64          `json:"id"`
	AccountID   int64          `json:"account_id"`
	Symbol      sql.NullString `json:"symbol"`
	Amount      sql.NullInt32  `json:"amount"`
	LastUpdated sql.NullTime   `json:"last_updated"`
}

type Trade struct {
	ID        int64          `json:"id"`
	AccountID int64          `json:"account_id"`
	Symbol    sql.NullString `json:"symbol"`
	// must be positive
	Amount    int32          `json:"amount"`
	Price     string         `json:"price"`
	TradeType sql.NullString `json:"trade_type"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
