// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type AuditLog struct {
	ID        int64
	AccountID int64
	Action    sql.NullString
	Timestamp sql.NullTime
}

type Deposit struct {
	ID        int64
	AccountID int64
	Amount    int64
	CreatedAt time.Time
}

type PortfolioBalance struct {
	ID          int64
	AccountID   int64
	Symbol      sql.NullString
	Amount      sql.NullInt32
	LastUpdated sql.NullTime
}

type Trade struct {
	ID        int64
	AccountID int64
	Symbol    sql.NullString
	// must be positive
	Amount    int32
	Price     string
	TradeType sql.NullString
	CreatedAt sql.NullTime
}

type User struct {
	ID          int64
	FullName    sql.NullString
	ContactInfo sql.NullString
	AccountID   int64
	CreatedAt   sql.NullTime
}
