// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateLogs(ctx context.Context, action sql.NullString) (AuditLog, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetTrade(ctx context.Context, id int64) (Trade, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]AuditLog, error)
	ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
}

var _ Querier = (*Queries)(nil)
